language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc

before_install:
  - git clone --branch=release --depth=1 https://github.com/jpcre2/pcre2
  - cd pcre2
  - autoreconf -v -i
  - make
  - sudo make install
  - cd -
script:
  - autoreconf -v -i
  - make
  - make check
