.TH "src Directory Reference" 3 "Mon Sep 5 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjpcre2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBjpcre2\&.hpp\fP"
.br
.RI "\fIMain header file for JPCRE library to be included by programs that call JPCRE2 functions\&. \fP"
.in -1c
