.TH "src Directory Reference" 3 "Tue Sep 6 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjpcre2\&.hpp\fP"
.br
.RI "\fIMain header file for JPCRE2 library to be included by programs that uses its functionalities\&. \fP"
.ti -1c
.RI "file \fBtest_match\&.cpp\fP"
.br
.RI "\fIAn example of performing regex match against a pattern with JPCRE2 and getting the match count and match results\&. \fP"
.ti -1c
.RI "file \fBtest_match2\&.cpp\fP"
.br
.RI "\fIContains an example to take subject string, pattern and modifier from user input and perform regex match using JPCRE2\&. \fP"
.ti -1c
.RI "file \fBtest_replace\&.cpp\fP"
.br
.RI "\fIAn example of doing regex replace with JPCRE2\&. \fP"
.ti -1c
.RI "file \fBtest_replace2\&.cpp\fP"
.br
.RI "\fIContains an example to take subject string, replacement string, modifier and pattern from user input and perform regex replace with JPCRE2\&. \fP"
.ti -1c
.RI "file \fBtest_shorts\&.cpp\fP"
.br
.RI "\fIContains some short examples of performing regex match and regex replace with JPCRE2\&. \fP"
.in -1c
