.TH "jpcre2.cpp" 3 "Mon Sep 5 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.cpp \- Defines all classes , functions, constants declared in the \fBjpcre2\&.hpp\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'jpcre2\&.hpp'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstring>\fP
.br

.SH "Detailed Description"
.PP 
Defines all classes , functions, constants declared in the \fBjpcre2\&.hpp\fP file\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
