.TH "jpcre2.hpp" 3 "Thu Sep 8 2016" "Version 10.25.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.hpp \- Main header file for JPCRE2 library to be included by programs that uses its functionalities\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <pcre2\&.h>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjpcre2::Except\fP"
.br
.RI "\fIClass to handle exception\&. \fP"
.ti -1c
.RI "class \fBjpcre2::RegexMatch\fP"
.br
.RI "\fIProvides the \fBRegexMatch::match()\fP function to perform regex matching\&. \fP"
.ti -1c
.RI "class \fBjpcre2::RegexReplace\fP"
.br
.RI "\fIProvides the \fBRegexReplace::replace()\fP function to perform regex replace on a string\&. \fP"
.ti -1c
.RI "class \fBjpcre2::Regex\fP"
.br
.RI "\fIImplements public overloaded and copy constructors, provides functions to set/unset various options and perform regex match and replace against a compiled pattern\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjpcre2\fP"
.br
.RI "\fITop level namespace of JPCRE2\&. \fP"
.ti -1c
.RI " \fBjpcre2::INFO\fP"
.br
.RI "\fINamespace to provide information about JPCRE2 library itself\&. \fP"
.ti -1c
.RI " \fBjpcre2::ERROR\fP"
.br
.RI "\fINamespace for error codes\&. \fP"
.ti -1c
.RI " \fBjpcre2::MOD\fP"
.br
.RI "\fINamespace for modifier constants\&. \fP"
.ti -1c
.RI " \fBjpcre2::utils\fP"
.br
.RI "\fINamespace for some utility functions\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCRE2_CODE_UNIT_WIDTH\fP   8"
.br
.RI "\fICode unit width 8 is used by default\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::size_t \fBjpcre2::SIZE_T\fP"
.br
.RI "\fIUsed for match count and vector size\&. \fP"
.ti -1c
.RI "typedef uint32_t \fBjpcre2::Uint\fP"
.br
.RI "\fIUsed for options (bitwise operation) \fP"
.ti -1c
.RI "typedef std::string \fBjpcre2::String\fP"
.br
.RI "\fIUsed as std::string\&. \fP"
.ti -1c
.RI "typedef std::map< String, String > \fBjpcre2::MapNas\fP"
.br
.RI "\fIMap for Named substrings\&. \fP"
.ti -1c
.RI "typedef std::map< SIZE_T, String > \fBjpcre2::MapNum\fP"
.br
.RI "\fIMap for Numbered substrings\&. \fP"
.ti -1c
.RI "typedef std::map< String, SIZE_T > \fBjpcre2::MapNtN\fP"
.br
.RI "\fISubstring name to Substring number map\&. \fP"
.ti -1c
.RI "typedef MapNtN \fBjpcre2::MapNtn\fP"
.br
.RI "\fIAllow spelling mistake of MapNtN as MapNtn\&. \fP"
.ti -1c
.RI "typedef std::vector< MapNas > \fBjpcre2::VecNas\fP"
.br
.RI "\fIVector of matches with named substrings\&. \fP"
.ti -1c
.RI "typedef std::vector< MapNtN > \fBjpcre2::VecNtN\fP"
.br
.RI "\fIVector of substring name to Substring number map\&. \fP"
.ti -1c
.RI "typedef VecNtN \fBjpcre2::VecNtn\fP"
.br
.RI "\fIAllow spelling mistake of VecNtN as VecNtn\&. \fP"
.ti -1c
.RI "typedef std::vector< MapNum > \fBjpcre2::VecNum\fP"
.br
.RI "\fIVector of matches with numbered substrings\&. \fP"
.in -1c
.SS "Enumerations"
.SS "Functions"

.in +1c
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (int)"
.br
.RI "\fIConverts an integer to String\&. \fP"
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (char)"
.br
.RI "\fIConverts a char to String\&. \fP"
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (const char *)"
.br
.RI "\fIConverts const char* to String\&. \fP"
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (PCRE2_UCHAR *)"
.br
.RI "\fIConverts a PCRE2_UCHAR* to String\&. \fP"
.ti -1c
.RI "std::string \fBjpcre2::utils::getPcre2ErrorMessage\fP (int)"
.br
.RI "\fIGet PCRE2 error message for an error number\&. \fP"
.ti -1c
.RI "std::string \fBjpcre2::utils::getErrorMessage\fP (int, int)"
.br
.RI "\fIGet error message from error number and error offset\&. \fP"
.ti -1c
.RI "void \fBjpcre2::utils::throwException\fP (int, int)"
.br
.RI "\fIUsed throughout JPCRE2 to throw exceptions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const String \fBjpcre2::INFO::NAME\fP"
.br
.RI "\fIName of the project\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::INFO::FULL_VERSION\fP"
.br
.RI "\fIFull version string\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::INFO::VERSION_GENRE\fP"
.br
.RI "\fIGeneration, depends on original PCRE2 version\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::INFO::VERSION_MAJOR\fP"
.br
.RI "\fIMajor version, updated when API change is made\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::INFO::VERSION_MINOR\fP"
.br
.RI "\fIMinor version, includes bug fix or minor feature upgrade\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::INFO::VERSION_PRE_RELEASE\fP"
.br
.RI "\fIAlpha or beta (testing) release version\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::C_N\fP"
.br
.RI "\fIString of compile modifier characters for PCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::C_V\fP []"
.br
.RI "\fIArray of compile modifier values for PCRE2 options\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::CJ_N\fP"
.br
.RI "\fIString of compile modifier characters for JPCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::CJ_V\fP []"
.br
.RI "\fIArray of compile modifier values for JPCRE2 options\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::M_N\fP"
.br
.RI "\fIString of action (match) modifier characters for PCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::M_V\fP []"
.br
.RI "\fIArray of action (match) modifier values for PCRE2 options\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::MJ_N\fP"
.br
.RI "\fIString of action (match) modifier characters for JPCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::MJ_V\fP []"
.br
.RI "\fIArray of action (match) modifier values for JPCRE2 options\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::R_N\fP"
.br
.RI "\fIString of action (replace) modifier characters for PCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::R_V\fP []"
.br
.RI "\fIArray of action (replace) modifier values for PCRE2 options\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::MOD::RJ_N\fP"
.br
.RI "\fIString of action (replace) modifier characters for JPCRE2 options\&. \fP"
.ti -1c
.RI "const Uint \fBjpcre2::MOD::RJ_V\fP []"
.br
.RI "\fIArray of action (replace) modifier values for JPCRE2 options\&. \fP"
.ti -1c
.RI "const SIZE_T \fBjpcre2::SUBSTITUTE_RESULT_INIT_SIZE\fP = std::numeric_limits<int>::max()"
.br
.RI "\fIUsed by default to provide big enough initial buffer for replaced string\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::LOCALE_NONE\fP = 'JPCRE2_NONE'"
.br
.RI "\fIDon't do anything about locale if it is set to \fBLOCALE_NONE\fP\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::LOCALE_DEFAULT\fP = LOCALE_NONE"
.br
.RI "\fIDefault locale\&. \fP"
.ti -1c
.RI "const String \fBjpcre2::JIT_ERROR_MESSAGE_PREFIX\fP = 'JIT compilation failed! '"
.br
.RI "\fIPrefix to be added to JIT error message\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Main header file for JPCRE2 library to be included by programs that uses its functionalities\&. 

It includes the pcre2\&.h header, therefore you shouldn't include pcre2\&.h separately in your program\&. Make sure to link both JPCRE2 and PCRE2 library when compiling\&.
.PP
If you are using JPCRE2 with all of its source files, you won't need to link it with JPCRE2 library, but do remember that you still need to link with PCRE2 library\&. 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
