.TH "jpcre2::utils" 3 "Sun Sep 11 2016" "Version 10.26.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::utils \- Namespace for some utility functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBString\fP \fBtoString\fP (int)"
.br
.RI "Converts an integer to String\&. "
.ti -1c
.RI "\fBString\fP \fBtoString\fP (char)"
.br
.RI "Converts a char to String\&. "
.ti -1c
.RI "\fBString\fP \fBtoString\fP (const char *)"
.br
.RI "Converts const char* to String\&. "
.ti -1c
.RI "\fBString\fP \fBtoString\fP (PCRE2_UCHAR *)"
.br
.RI "Converts a PCRE2_UCHAR* to String\&. "
.ti -1c
.RI "std::string \fBgetPcre2ErrorMessage\fP (int)"
.br
.RI "Get PCRE2 error message for an error number\&. "
.ti -1c
.RI "std::string \fBgetErrorMessage\fP (int, int)"
.br
.RI "Get error message from error number and error offset\&. "
.ti -1c
.RI "std::string \fBgetWarningMessage\fP (int, int)"
.br
.RI "Get warning message from warning number and offset\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace for some utility functions\&. 
.SH "Function Documentation"
.PP 
.SS "std::string jpcre2::utils::getErrorMessage (int err_num, int err_off)"

.PP
Get error message from error number and error offset\&. Return error message according to error number and error offset\&.
.PP
\fBParameters:\fP
.RS 4
\fIerr_num\fP Error number 
.br
\fIerr_off\fP Error offset 
.RE
.PP
\fBReturns:\fP
.RS 4
Error message as a string 
.RE
.PP

.SS "std::string jpcre2::utils::getPcre2ErrorMessage (int err_num)"

.PP
Get PCRE2 error message for an error number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerr_num\fP PCRE2 error number 
.RE
.PP
\fBReturns:\fP
.RS 4
Error message as \fBjpcre2::String\fP 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::utils::toString (int x)"

.PP
Converts an integer to String\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Integer to be converted to \fBjpcre2::String\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBjpcre2::String\fP 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::utils::toString (char a)"

.PP
Converts a char to String\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP char to be converted to \fBjpcre2::String\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBjpcre2::String\fP 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::utils::toString (const char * a)"

.PP
Converts const char* to String\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP const char* to be converted to \fBjpcre2::String\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBjpcre2::String\fP 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::utils::toString (PCRE2_UCHAR * a)"

.PP
Converts a PCRE2_UCHAR* to String\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP PCRE2_UCHAR* to be converted to \fBjpcre2::String\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBjpcre2::String\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
