.TH "jpcre2.cpp" 3 "Sun Sep 4 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'jpcre2\&.hpp'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstring>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
