.TH "jpcre2::INFO" 3 "Wed Sep 7 2016" "Version 10.25.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::INFO \- Namespace to provide information about JPCRE2 library itself\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBString\fP \fBNAME\fP"
.br
.RI "\fIName of the project\&. \fP"
.ti -1c
.RI "const \fBString\fP \fBFULL_VERSION\fP"
.br
.RI "\fIFull version string\&. \fP"
.ti -1c
.RI "const \fBString\fP \fBVERSION_GENRE\fP"
.br
.RI "\fIGeneration, depends on original PCRE2 version\&. \fP"
.ti -1c
.RI "const \fBString\fP \fBVERSION_MAJOR\fP"
.br
.RI "\fIMajor version, updated when API change is made\&. \fP"
.ti -1c
.RI "const \fBString\fP \fBVERSION_MINOR\fP"
.br
.RI "\fIMinor version, includes bug fix or minor feature upgrade\&. \fP"
.ti -1c
.RI "const \fBString\fP \fBVERSION_PRE_RELEASE\fP"
.br
.RI "\fIAlpha or beta (testing) release version\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Namespace to provide information about JPCRE2 library itself\&. 

Contains constant Strings with version info\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBjpcre2::String\fP jpcre2::INFO::NAME"

.PP
Name of the project\&. 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
