.TH "jpcre2.hpp" 3 "Sun Sep 11 2016" "Version 10.26.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.hpp \- Main header file for JPCRE2 library to be included by programs that uses its functionalities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjpcre2::RegexMatch\fP"
.br
.RI "Provides the \fBRegexMatch::match()\fP function to perform regex matching\&. "
.ti -1c
.RI "class \fBjpcre2::RegexReplace\fP"
.br
.RI "Provides the \fBRegexReplace::replace()\fP function to perform regex replace on a string\&. "
.ti -1c
.RI "class \fBjpcre2::Regex\fP"
.br
.RI "Implements public overloaded and copy constructors, provides functions to set/unset various options and perform regex match and replace against a compiled pattern\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjpcre2\fP"
.br
.RI "Top level namespace of JPCRE2\&. "
.ti -1c
.RI " \fBjpcre2::INFO\fP"
.br
.RI "Namespace to provide information about JPCRE2 library itself\&. "
.ti -1c
.RI " \fBjpcre2::ERROR\fP"
.br
.RI "Namespace for error codes\&. "
.ti -1c
.RI " \fBjpcre2::MOD\fP"
.br
.RI "Namespace for modifier constants\&. "
.ti -1c
.RI " \fBjpcre2::utils\fP"
.br
.RI "Namespace for some utility functions\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::size_t \fBjpcre2::SIZE_T\fP"
.br
.RI "Used for match count and vector size\&. "
.ti -1c
.RI "typedef uint32_t \fBjpcre2::Uint\fP"
.br
.RI "Used for options (bitwise operation) "
.ti -1c
.RI "typedef std::string \fBjpcre2::String\fP"
.br
.RI "Used as std::string\&. "
.ti -1c
.RI "typedef std::map< String, String > \fBjpcre2::MapNas\fP"
.br
.RI "Map for Named substrings\&. "
.ti -1c
.RI "typedef std::map< SIZE_T, String > \fBjpcre2::MapNum\fP"
.br
.RI "Map for Numbered substrings\&. "
.ti -1c
.RI "typedef std::map< String, SIZE_T > \fBjpcre2::MapNtN\fP"
.br
.RI "Substring name to Substring number map\&. "
.ti -1c
.RI "typedef MapNtN \fBjpcre2::MapNtn\fP"
.br
.RI "Allow spelling mistake of MapNtN as MapNtn\&. "
.ti -1c
.RI "typedef std::vector< MapNas > \fBjpcre2::VecNas\fP"
.br
.RI "Vector of matches with named substrings\&. "
.ti -1c
.RI "typedef std::vector< MapNtN > \fBjpcre2::VecNtN\fP"
.br
.RI "Vector of substring name to Substring number map\&. "
.ti -1c
.RI "typedef VecNtN \fBjpcre2::VecNtn\fP"
.br
.RI "Allow spelling mistake of VecNtN as VecNtn\&. "
.ti -1c
.RI "typedef std::vector< MapNum > \fBjpcre2::VecNum\fP"
.br
.RI "Vector of matches with numbered substrings\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBjpcre2::NONE\fP = 0x0000000u, \fBjpcre2::FIND_ALL\fP = 0x0000002u, \fBjpcre2::JIT_COMPILE\fP = 0x0000004u }
.RI "These constants provide JPCRE2 options\&. ""
.br
.ti -1c
.RI "enum { \fBjpcre2::ERROR::INVALID_MODIFIER\fP = 2, \fBjpcre2::ERROR::JIT_COMPILE_FAILED\fP = 3 }
.RI "ERROR numbers\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (int)"
.br
.RI "Converts an integer to String\&. "
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (char)"
.br
.RI "Converts a char to String\&. "
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (const char *)"
.br
.RI "Converts const char* to String\&. "
.ti -1c
.RI "String \fBjpcre2::utils::toString\fP (PCRE2_UCHAR *)"
.br
.RI "Converts a PCRE2_UCHAR* to String\&. "
.ti -1c
.RI "std::string \fBjpcre2::utils::getPcre2ErrorMessage\fP (int)"
.br
.RI "Get PCRE2 error message for an error number\&. "
.ti -1c
.RI "std::string \fBjpcre2::utils::getErrorMessage\fP (int, int)"
.br
.RI "Get error message from error number and error offset\&. "
.ti -1c
.RI "std::string \fBjpcre2::utils::getWarningMessage\fP (int, int)"
.br
.RI "Get warning message from warning number and offset\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBjpcre2::INFO::NAME\fP"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "const std::string \fBjpcre2::INFO::FULL_VERSION\fP"
.br
.RI "Full version string\&. "
.ti -1c
.RI "const std::string \fBjpcre2::INFO::VERSION_GENRE\fP"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "const std::string \fBjpcre2::INFO::VERSION_MAJOR\fP"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "const std::string \fBjpcre2::INFO::VERSION_MINOR\fP"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "const std::string \fBjpcre2::INFO::VERSION_PRE_RELEASE\fP"
.br
.RI "Alpha or beta (testing) release version\&. "
.ti -1c
.RI "const SIZE_T \fBjpcre2::SUBSTITUTE_RESULT_INIT_SIZE\fP = std::numeric_limits<int>::max()"
.br
.RI "Used by default to provide big enough initial buffer for replaced string\&. "
.ti -1c
.RI "const String \fBjpcre2::LOCALE_NONE\fP = 'JPCRE2_NONE'"
.br
.RI "Don't do anything about locale if it is set to \fBjpcre2::LOCALE_NONE\fP\&. "
.ti -1c
.RI "const String \fBjpcre2::LOCALE_DEFAULT\fP = LOCALE_NONE"
.br
.RI "Default locale\&. "
.ti -1c
.RI "const String \fBjpcre2::JIT_ERROR_MESSAGE_PREFIX\fP = 'JIT compilation failed! '"
.br
.RI "Prefix to be added to JIT error message\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::C_N\fP"
.br
.RI "String of compile modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::C_V\fP []"
.br
.RI "Array of compile modifier values for PCRE2 options\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::CJ_N\fP"
.br
.RI "String of compile modifier characters for JPCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::CJ_V\fP []"
.br
.RI "Array of compile modifier values for JPCRE2 options\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::M_N\fP"
.br
.RI "String of action (match) modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::M_V\fP []"
.br
.RI "Array of action (match) modifier values for PCRE2 options\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::MJ_N\fP"
.br
.RI "String of action (match) modifier characters for JPCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::MJ_V\fP []"
.br
.RI "Array of action (match) modifier values for JPCRE2 options\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::R_N\fP"
.br
.RI "String of action (replace) modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::R_V\fP []"
.br
.RI "Array of action (replace) modifier values for PCRE2 options\&. "
.ti -1c
.RI "const String \fBjpcre2::MOD::RJ_N\fP"
.br
.RI "String of action (replace) modifier characters for JPCRE2 options\&. "
.ti -1c
.RI "const Uint \fBjpcre2::MOD::RJ_V\fP []"
.br
.RI "Array of action (replace) modifier values for JPCRE2 options\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main header file for JPCRE2 library to be included by programs that uses its functionalities\&. 

It includes the pcre2\&.h header, therefore you shouldn't include pcre2\&.h separately in your program\&. Make sure to link both JPCRE2 and PCRE2 library when compiling\&.
.PP
If you are using JPCRE2 with all of its source files, you won't need to link it with JPCRE2 library, but do remember that you still need to link with PCRE2 library\&. 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
