.TH "jpcre2" 3 "Sun Sep 11 2016" "Version 10.26.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2 \- Top level namespace of JPCRE2\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBERROR\fP"
.br
.RI "Namespace for error codes\&. "
.ti -1c
.RI " \fBINFO\fP"
.br
.RI "Namespace to provide information about JPCRE2 library itself\&. "
.ti -1c
.RI " \fBMOD\fP"
.br
.RI "Namespace for modifier constants\&. "
.ti -1c
.RI " \fButils\fP"
.br
.RI "Namespace for some utility functions\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegex\fP"
.br
.RI "Implements public overloaded and copy constructors, provides functions to set/unset various options and perform regex match and replace against a compiled pattern\&. "
.ti -1c
.RI "class \fBRegexMatch\fP"
.br
.RI "Provides the \fBRegexMatch::match()\fP function to perform regex matching\&. "
.ti -1c
.RI "class \fBRegexReplace\fP"
.br
.RI "Provides the \fBRegexReplace::replace()\fP function to perform regex replace on a string\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::size_t \fBSIZE_T\fP"
.br
.RI "Used for match count and vector size\&. "
.ti -1c
.RI "typedef uint32_t \fBUint\fP"
.br
.RI "Used for options (bitwise operation) "
.ti -1c
.RI "typedef std::string \fBString\fP"
.br
.RI "Used as std::string\&. "
.ti -1c
.RI "typedef std::map< \fBString\fP, \fBString\fP > \fBMapNas\fP"
.br
.RI "Map for Named substrings\&. "
.ti -1c
.RI "typedef std::map< \fBSIZE_T\fP, \fBString\fP > \fBMapNum\fP"
.br
.RI "Map for Numbered substrings\&. "
.ti -1c
.RI "typedef std::map< \fBString\fP, \fBSIZE_T\fP > \fBMapNtN\fP"
.br
.RI "Substring name to Substring number map\&. "
.ti -1c
.RI "typedef \fBMapNtN\fP \fBMapNtn\fP"
.br
.RI "Allow spelling mistake of MapNtN as MapNtn\&. "
.ti -1c
.RI "typedef std::vector< \fBMapNas\fP > \fBVecNas\fP"
.br
.RI "Vector of matches with named substrings\&. "
.ti -1c
.RI "typedef std::vector< \fBMapNtN\fP > \fBVecNtN\fP"
.br
.RI "Vector of substring name to Substring number map\&. "
.ti -1c
.RI "typedef \fBVecNtN\fP \fBVecNtn\fP"
.br
.RI "Allow spelling mistake of VecNtN as VecNtn\&. "
.ti -1c
.RI "typedef std::vector< \fBMapNum\fP > \fBVecNum\fP"
.br
.RI "Vector of matches with numbered substrings\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNONE\fP = 0x0000000u, \fBFIND_ALL\fP = 0x0000002u, \fBJIT_COMPILE\fP = 0x0000004u }
.RI "These constants provide JPCRE2 options\&. ""
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSIZE_T\fP \fBSUBSTITUTE_RESULT_INIT_SIZE\fP = std::numeric_limits<int>::max()"
.br
.RI "Used by default to provide big enough initial buffer for replaced string\&. "
.ti -1c
.RI "const \fBString\fP \fBLOCALE_NONE\fP = 'JPCRE2_NONE'"
.br
.RI "Don't do anything about locale if it is set to \fBjpcre2::LOCALE_NONE\fP\&. "
.ti -1c
.RI "const \fBString\fP \fBLOCALE_DEFAULT\fP = \fBLOCALE_NONE\fP"
.br
.RI "Default locale\&. "
.ti -1c
.RI "const \fBString\fP \fBJIT_ERROR_MESSAGE_PREFIX\fP = 'JIT compilation failed! '"
.br
.RI "Prefix to be added to JIT error message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Top level namespace of JPCRE2\&. 

All functions, classes, constants, enums that are provided by JPCRE2 belong to this namespace while \fBPCRE2\fP functions, constants remain outside of its scope\&.
.PP
If you want to use any PCRE2 functions or constants, remember that they are in the global scope and should be used as such\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
These constants provide JPCRE2 options\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
Option 0 (zero) 
.TP
\fB\fIFIND_ALL \fP\fP
Find all during match (global match) 
.TP
\fB\fIJIT_COMPILE \fP\fP
Perform JIT compilation for optimization\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBjpcre2::String\fP jpcre2::LOCALE_DEFAULT = \fBLOCALE_NONE\fP"

.PP
Default locale\&. Default local to be used\&. 
.SS "const \fBjpcre2::String\fP jpcre2::LOCALE_NONE = 'JPCRE2_NONE'"

.PP
Don't do anything about locale if it is set to \fBjpcre2::LOCALE_NONE\fP\&. Nothing to be done on locale\&. 
.SS "const \fBjpcre2::SIZE_T\fP jpcre2::SUBSTITUTE_RESULT_INIT_SIZE = std::numeric_limits<int>::max()"

.PP
Used by default to provide big enough initial buffer for replaced string\&. Max of \fCint\fP is used as the initial size of replaced string by default\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
