.TH "jpcre2::RegexReplace" 3 "Wed Sep 7 2016" "Version 10.25.02" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::RegexReplace \- Provides the \fBRegexReplace::replace()\fP function to perform regex replace on a string\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetSubject\fP (const \fBString\fP &s)"
.br
.RI "\fISet the subject string \fBr_subject\fP\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetReplaceWith\fP (const \fBString\fP &s)"
.br
.RI "\fISet the replacement string \fBr_replw\fP\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetModifier\fP (const \fBString\fP &s)"
.br
.RI "\fISet the modifier string (overwrites existing JPCRE2 and PCRE2 option)\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetBufferSize\fP (PCRE2_SIZE x)"
.br
.RI "\fISet the initial buffer size (\fBbuffer_size\fP) to be allocated for replaced string (used by PCRE2) \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetJpcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fISet JPCRE2 option \fBjpcre2_replace_opts\fP (overwrite existing option) \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBsetPcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fISet PCRE2 option \fBreplace_opts\fP (overwrite existing option) \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBchangeModifier\fP (const \fBString\fP &mod, bool x)"
.br
.RI "\fIParse modifier and add/remove equivalent PCRE2 and JPCRE2 options\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBchangeJpcre2Option\fP (\fBUint\fP opt, bool x)"
.br
.RI "\fIAdd or remove a JPCRE2 option\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBchangePcre2Option\fP (\fBUint\fP opt, bool x)"
.br
.RI "\fIAdd or remove a PCRE2 option\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBaddModifier\fP (const \fBString\fP &mod)"
.br
.RI "\fIParse modifier string and add equivalent PCRE2 and JPCRE2 options\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBaddJpcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIAdd specified JPCRE2 option to existing options \fBjpcre2_replace_opts\fP\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBaddPcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIAdd specified PCRE2 option to existing options \fBreplace_opts\fP\&. \fP"
.ti -1c
.RI "\fBString\fP \fBreplace\fP (void)"
.br
.RI "\fIReturns the resultant string after performing regex replace\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit_vars\fP ()"
.br
.RI "\fIInitialize class variables\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP (const \fBRegexReplace\fP &)"
.br
.RI "\fIThis is a copy constructor which is only used to prevent public object creation\&. \fP"
.ti -1c
.RI "\fB~RegexReplace\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRegex\fP * \fBre\fP"
.br
.RI "\fIThis is used to access private members in \fBRegex\fP\&. \fP"
.ti -1c
.RI "\fBString\fP \fBr_subject\fP"
.br
.RI "\fISubject string for replace\&. \fP"
.ti -1c
.RI "\fBString\fP \fBr_replw\fP"
.br
.RI "\fIReplacement string i\&.e string to replace with\&. \fP"
.ti -1c
.RI "\fBUint\fP \fBreplace_opts\fP"
.br
.RI "\fIPCRE2 options for pcre2_substitute() (PCRE2 internal function) \fP"
.ti -1c
.RI "\fBUint\fP \fBjpcre2_replace_opts\fP"
.br
.RI "\fIJPCRE2 options\&. \fP"
.ti -1c
.RI "PCRE2_SIZE \fBbuffer_size\fP"
.br
.RI "\fISize of the resultant string after replacement\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRegex\fP"
.br
.RI "\fIDefine \fBRegex\fP as a friend so that it can create object of this class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides the \fBRegexReplace::replace()\fP function to perform regex replace on a string\&. 

Provides chained methods to set various options\&.
.PP
All constructors of this class are private\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpcre2::RegexReplace::RegexReplace ()\fC [inline]\fP, \fC [private]\fP"

.PP
Default constructor\&. Initialize class variables 
.SS "jpcre2::RegexReplace::RegexReplace (const \fBRegexReplace\fP &)\fC [inline]\fP, \fC [private]\fP"

.PP
This is a copy constructor which is only used to prevent public object creation\&. No need to implement it completely 
.SS "jpcre2::RegexReplace::~RegexReplace ()\fC [inline]\fP, \fC [private]\fP"

.PP
Destructor\&. Nothing to be done here\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::addJpcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Add specified JPCRE2 option to existing options \fBjpcre2_replace_opts\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::addJpcre2Option()\fP 
.PP
\fBRegex::addJpcre2Option()\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::addModifier (const \fBString\fP & mod)\fC [inline]\fP"

.PP
Parse modifier string and add equivalent PCRE2 and JPCRE2 options\&. This is just a wrapper of the original function \fBRegexReplace::changeModifier()\fP provided for convenience\&.
.PP
\fBNote:\fP If speed of operation is very crucial, use \fBRegexReplace::addJpcre2Option()\fP and \fBRegexReplace::addPcre2Option()\fP with equivalent options\&. It will be faster that way\&. 
.PP
\fBParameters:\fP
.RS 4
\fImod\fP Modifier string 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::addModifier()\fP 
.PP
\fBRegex::addModifier()\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::addPcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Add specified PCRE2 option to existing options \fBreplace_opts\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::addPcre2Option()\fP 
.PP
\fBRegex::addPcre2Option()\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::changeJpcre2Option (\fBUint\fP opt, bool x)\fC [inline]\fP"

.PP
Add or remove a JPCRE2 option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIopt\fP JPCRE2 option value 
.br
\fIx\fP Add the option if it's true, remove otherwise\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegex\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::changeJpcre2Option()\fP 
.PP
\fBRegex::changeJpcre2Option()\fP 
.RE
.PP

.SS "\fBjpcre2::RegexReplace\fP & jpcre2::RegexReplace::changeModifier (const \fBString\fP & mod, bool x)"

.PP
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options\&. After a call to this function \fBreplace_opts\fP and \fBjpcre2_replace_opts\fP will be properly set\&. This function does not initialize or re-initialize options\&. If you want to set options from scratch, initialize them to their defaults before calling this function\&.
.PP
\fBNote:\fP If speed of operation is very crucial, use \fBRegexReplace::changeJpcre2Option()\fP and \fBRegexReplace::changePcre2Option()\fP with equivalent options\&. It will be faster that way\&. 
.PP
\fBParameters:\fP
.RS 4
\fImod\fP Modifier string 
.br
\fIx\fP Whether to add or remove option 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::changeModifier()\fP 
.PP
\fBRegex::changeModifier()\fP 
.RE
.PP

.PP
References jpcre2::Regex::changeJpcre2Option(), jpcre2::Regex::changePcre2Option(), jpcre2::ERROR_ALL, jpcre2::ERROR::INVALID_MODIFIER, jpcre2::MOD::R_N, jpcre2::MOD::R_V, jpcre2::MOD::RJ_N, jpcre2::MOD::RJ_V, jpcre2::utils::throwException(), and jpcre2::VALIDATE_MODIFIER\&.
.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::changePcre2Option (\fBUint\fP opt, bool x)\fC [inline]\fP"

.PP
Add or remove a PCRE2 option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIopt\fP PCRE2 option value 
.br
\fIx\fP Add the option if it's true, remove otherwise\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegex\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::changePcre2Option()\fP 
.PP
\fBRegex::changePcre2Option()\fP 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::RegexReplace::replace (void)"

.PP
Returns the resultant string after performing regex replace\&. Retrieves subject string, replacement string, modifier and other options from class variables\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBRegex::error_number\fP\fP Throws exception (error number) if error occurs\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Replaced string 
.RE
.PP

.PP
References jpcre2::Regex::replace(), jpcre2::utils::throwException(), and jpcre2::utils::toString()\&.
.PP
Referenced by jpcre2::Regex::replace()\&.
.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setBufferSize (PCRE2_SIZE x)\fC [inline]\fP"

.PP
Set the initial buffer size (\fBbuffer_size\fP) to be allocated for replaced string (used by PCRE2) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Buffer size 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setJpcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Set JPCRE2 option \fBjpcre2_replace_opts\fP (overwrite existing option) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::setJpcre2Option()\fP 
.PP
\fBRegex::setJpcre2Option()\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setModifier (const \fBString\fP & s)\fC [inline]\fP"

.PP
Set the modifier string (overwrites existing JPCRE2 and PCRE2 option)\&. \fBNote:\fP If speed of operation is very crucial, use \fBRegexReplace::setJpcre2Option()\fP and \fBRegexReplace::setPcre2Option()\fP with equivalent options\&. It will be faster that way\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP Modifier string 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::setModifier()\fP 
.PP
\fBRegex::setModifier()\fP 
.RE
.PP

.PP
Referenced by jpcre2::Regex::replace()\&.
.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setPcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Set PCRE2 option \fBreplace_opts\fP (overwrite existing option) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::setPcre2Option()\fP 
.PP
\fBRegex::setPcre2Option()\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setReplaceWith (const \fBString\fP & s)\fC [inline]\fP"

.PP
Set the replacement string \fBr_replw\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP String to replace with 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP

.PP
Referenced by jpcre2::Regex::replace()\&.
.SS "\fBRegexReplace\fP& jpcre2::RegexReplace::setSubject (const \fBString\fP & s)\fC [inline]\fP"

.PP
Set the subject string \fBr_subject\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP Subject string 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRegexReplace\fP& 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::setSubject()\fP 
.RE
.PP

.PP
Referenced by jpcre2::Regex::replace()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
