.TH "jpcre2::utils" 3 "Tue Sep 6 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::utils \- Namespace for some utility functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBString\fP \fBtoString\fP (int a)"
.br
.RI "\fIConverts an integer to String\&. \fP"
.ti -1c
.RI "\fBString\fP \fBtoString\fP (char a)"
.br
.RI "\fIConverts a char to String\&. \fP"
.ti -1c
.RI "\fBString\fP \fBtoString\fP (const char *a)"
.br
.RI "\fIConverts const char* to String\&. \fP"
.ti -1c
.RI "\fBString\fP \fBtoString\fP (PCRE2_UCHAR *a)"
.br
.RI "\fIConverts a PCRE2_UCHAR* to String\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetPcre2ErrorMessage\fP (int err_num)"
.br
.RI "\fIGet PCRE2 error message for an error number\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Namespace for some utility functions\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
