.TH "jpcre2::Regex" 3 "Mon Sep 5 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::Regex \- This is the main class that is to be used to perform all JPCRE2 related actions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegex\fP ()"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "\fBRegex\fP (const \fBString\fP &re)"
.br
.RI "\fICompiles pattern with initialization\&. \fP"
.ti -1c
.RI "\fBRegex\fP (const \fBString\fP &re, const \fBString\fP &mod)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. \fP"
.ti -1c
.RI "\fBRegex\fP (const \fBString\fP &re, \fBUint\fP pcre2_opts)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. \fP"
.ti -1c
.RI "\fBRegex\fP (const \fBString\fP &re, \fBUint\fP pcre2_opts, \fBUint\fP opt_bits)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. \fP"
.ti -1c
.RI "\fBRegex\fP (const \fBRegex\fP &r)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Copy constructor. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBoperator=\fP (const \fBRegex\fP &r)"
.br
.RI "\fIOverloaded assignment operator\&. \fP"
.ti -1c
.RI "\fB~Regex\fP ()"
.br
.RI "\fIDestructor (deletes memory used) \fP"
.ti -1c
.RI "\fBRegex\fP & \fBreset\fP ()"
.br
.RI "\fIReset all class variables to its default (initial) state\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetModifier\fP ()"
.br
.RI "\fIGet modifier string\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetPattern\fP ()"
.br
.RI "\fIGet pattern string\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetLocale\fP ()"
.br
.RI "\fIGet locale as a string\&. \fP"
.ti -1c
.RI "\fBUint\fP \fBgetPcre2Option\fP ()"
.br
.RI "\fIGet PCRE2 option\&. \fP"
.ti -1c
.RI "\fBUint\fP \fBgetJpcre2Option\fP ()"
.br
.RI "\fIGet JPCRE2 option\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetErrorMessage\fP (int err_num, PCRE2_SIZE err_off)"
.br
.RI "\fIReturn error message by error number and error offset\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetErrorMessage\fP (int err_num)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Uses class variable error_offest as error offset\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetErrorMessage\fP ()"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Uses class variable error_number as error number and error_offest as error offset\&. \fP"
.ti -1c
.RI "\fBString\fP \fBgetWarningMessage\fP ()"
.br
.RI "\fIGet current warning message\&. \fP"
.ti -1c
.RI "int \fBgetErrorNumber\fP ()"
.br
.RI "\fIreturn \fBerror_number\fP \fP"
.ti -1c
.RI "PCRE2_SIZE \fBgetErrorOffset\fP ()"
.br
.RI "\fIreturn \fBerror_offset\fP \fP"
.ti -1c
.RI "\fBRegex\fP & \fBsetPattern\fP (const \fBString\fP &re)"
.br
.RI "\fISet the Pattern string\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBsetModifier\fP (const \fBString\fP &x)"
.br
.RI "\fISet the modifier (overwrites existing JPCRE2 and PCRE2 option)\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBsetLocale\fP (const \fBString\fP &x)"
.br
.RI "\fISet the locale\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBsetJpcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fISet JPCRE2 option (overwrites existing option) \fP"
.ti -1c
.RI "\fBRegex\fP & \fBsetPcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fISet PCRE2 option (overwrites existing option) \fP"
.ti -1c
.RI "\fBRegex\fP & \fBaddJpcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIAdd option to existing JPCRE2 options\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBaddPcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIAdd option to existing PCRE2 options\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBremoveJpcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIRemove option from existing JPCRE2 option\&. \fP"
.ti -1c
.RI "\fBRegex\fP & \fBremovePcre2Option\fP (\fBUint\fP x)"
.br
.RI "\fIRemove option from existing PCRE2 option\&. \fP"
.ti -1c
.RI "void \fBcompile\fP (void)"
.br
.RI "\fICompiles the regex using values from class variables\&. \fP"
.ti -1c
.RI "void \fBcompile\fP (const \fBString\fP &re, \fBUint\fP po, \fBUint\fP jo)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. \fP"
.ti -1c
.RI "void \fBcompile\fP (const \fBString\fP &re, \fBUint\fP po)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. \fP"
.ti -1c
.RI "void \fBcompile\fP (const \fBString\fP &re, const \fBString\fP &mod)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. \fP"
.ti -1c
.RI "void \fBcompile\fP (const \fBString\fP &re)"
.br
.RI "\fIThis is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. \fP"
.ti -1c
.RI "\fBSIZE_T\fP \fBmatch\fP (const \fBString\fP &s, const \fBString\fP &mod)"
.br
.RI "\fIPerform regex match\&. \fP"
.ti -1c
.RI "\fBSIZE_T\fP \fBmatch\fP (const \fBString\fP &s)"
.br
.RI "\fIPerform regex match\&. \fP"
.ti -1c
.RI "\fBRegexMatch\fP & \fBinitMatch\fP ()"
.br
.RI "\fIPrepare to call \fBRegexMatch::match()\fP\&. \fP"
.ti -1c
.RI "\fBString\fP \fBreplace\fP (const \fBString\fP &mains, const \fBString\fP &repl, const \fBString\fP &mod)"
.br
.RI "\fIPerform regex replace\&. \fP"
.ti -1c
.RI "\fBString\fP \fBreplace\fP (const \fBString\fP &mains, const \fBString\fP &repl)"
.br
.RI "\fIPerform regex replace\&. \fP"
.ti -1c
.RI "\fBString\fP \fBreplace\fP (const \fBString\fP &mains)"
.br
.RI "\fIPerform regex replace\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP & \fBinitReplace\fP ()"
.br
.RI "\fIPrepare to call \fBRegexReplace::replace()\fP\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRegexMatch\fP * \fBrm\fP"
.br
.RI "\fIPointer to \fBRegexMatch\fP object\&. \fP"
.ti -1c
.RI "\fBRegexReplace\fP * \fBrr\fP"
.br
.RI "\fIPointer to \fBRegexReplace\fP object\&. \fP"
.ti -1c
.RI "\fBString\fP \fBpat_str\fP"
.br
.RI "\fIPattern string\&. \fP"
.ti -1c
.RI "\fBString\fP \fBmodifier\fP"
.br
.RI "\fIModifier string\&. \fP"
.ti -1c
.RI "pcre2_code * \fBcode\fP"
.br
.RI "\fICompiled pattern (code) \fP"
.ti -1c
.RI "int \fBerror_number\fP"
.br
.RI "\fIError number\&. \fP"
.ti -1c
.RI "PCRE2_SIZE \fBerror_offset\fP"
.br
.RI "\fIError offset\&. \fP"
.ti -1c
.RI "\fBUint\fP \fBcompile_opts\fP"
.br
.RI "\fICompile options\&. \fP"
.ti -1c
.RI "\fBUint\fP \fBjpcre2_compile_opts\fP"
.br
.RI "\fICompile options specific to JPCRE2\&. \fP"
.ti -1c
.RI "\fBString\fP \fBmylocale\fP"
.br
.RI "\fILocale string\&. \fP"
.ti -1c
.RI "\fBString\fP \fBcurrent_warning_msg\fP"
.br
.RI "\fIcurrent warning message \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the main class that is to be used to perform all JPCRE2 related actions\&. 

This class implements public default constructor, deep copy constructor and overloaded assignment operator\&.
.PP
An object of this class must be created (can be temporary) to access its public functions and perform match or replace against a compiled pattern\&.
.PP
A pattern must be compiled either by explicitly calling the compile function or using one of the parameterized constructors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpcre2::Regex::Regex ()\fC [inline]\fP"

.PP
Default Constructor\&. Initializes all class variables to defaults\&. Does not perform any compilation\&. 
.SS "jpcre2::Regex::Regex (const \fBString\fP & re)\fC [inline]\fP"

.PP
Compiles pattern with initialization\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.RE
.PP

.SS "jpcre2::Regex::Regex (const \fBString\fP & re, const \fBString\fP & mod)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fImod\fP Modifier string 
.RE
.PP

.SS "jpcre2::Regex::Regex (const \fBString\fP & re, \fBUint\fP pcre2_opts)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fIpcre2_opts\fP PCRE2 option value 
.RE
.PP

.SS "jpcre2::Regex::Regex (const \fBString\fP & re, \fBUint\fP pcre2_opts, \fBUint\fP opt_bits)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Compiles pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fIpcre2_opts\fP PCRE2 option value 
.br
\fIopt_bits\fP JPCRE2 option value 
.RE
.PP

.SS "jpcre2::Regex::Regex (const \fBRegex\fP & r)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Copy constructor. Compiles pattern and Performs a deep copy\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBRegex\fP& jpcre2::Regex::addJpcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Add option to existing JPCRE2 options\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::addPcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Add option to existing PCRE2 options\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "void jpcre2::Regex::compile (const \fBString\fP & re, \fBUint\fP po, \fBUint\fP jo)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fIpo\fP PCRE2 option 
.br
\fIjo\fP JPCRE2 option 
.RE
.PP

.SS "void jpcre2::Regex::compile (const \fBString\fP & re, \fBUint\fP po)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fIpo\fP PCRE2 option 
.RE
.PP

.SS "void jpcre2::Regex::compile (const \fBString\fP & re, const \fBString\fP & mod)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.br
\fImod\fP Modifier string 
.RE
.PP

.SS "void jpcre2::Regex::compile (const \fBString\fP & re)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Initializes with class variables, sets the specified parameters, then compiles the pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.RE
.PP

.SS "\fBjpcre2::String\fP jpcre2::Regex::getErrorMessage (int err_num, PCRE2_SIZE err_off)"

.PP
Return error message by error number and error offset\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerr_num\fP Error number 
.br
\fIerr_off\fP Error offset 
.RE
.PP
\fBReturns:\fP
.RS 4
Error message as a string 
.RE
.PP

.PP
References code, compile_opts, current_warning_msg, jpcre2::ERROR_ALL, error_number, error_offset, jpcre2::utils::getPcre2ErrorMessage(), jpcre2::ERROR::INVALID_MODIFIER, jpcre2::JIT_COMPILE, jpcre2::ERROR::JIT_COMPILE_FAILED, jpcre2::JIT_ERROR_MESSAGE_PREFIX, jpcre2_compile_opts, modifier, rm, rr, jpcre2::utils::toString(), and jpcre2::VALIDATE_MODIFIER\&.
.SS "\fBString\fP jpcre2::Regex::getErrorMessage (int err_num)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Uses class variable error_offest as error offset\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerr_num\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Error message as a string 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::getErrorMessage ()\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Uses class variable error_number as error number and error_offest as error offset\&. 
.PP
\fBReturns:\fP
.RS 4
Error message as a string (empty if there is no error) 
.RE
.PP

.SS "\fBUint\fP jpcre2::Regex::getJpcre2Option ()\fC [inline]\fP"

.PP
Get JPCRE2 option\&. 
.PP
\fBReturns:\fP
.RS 4
\fBjpcre2_compile_opts\fP 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::getLocale ()\fC [inline]\fP"

.PP
Get locale as a string\&. 
.PP
\fBReturns:\fP
.RS 4
\fBmylocale\fP 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::getModifier ()\fC [inline]\fP"

.PP
Get modifier string\&. 
.PP
\fBReturns:\fP
.RS 4
\fBmodifier\fP 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::getPattern ()\fC [inline]\fP"

.PP
Get pattern string\&. 
.PP
\fBReturns:\fP
.RS 4
\fBpat_str\fP 
.RE
.PP

.SS "\fBUint\fP jpcre2::Regex::getPcre2Option ()\fC [inline]\fP"

.PP
Get PCRE2 option\&. 
.PP
\fBReturns:\fP
.RS 4
\fBcompile_opts\fP 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::getWarningMessage ()\fC [inline]\fP"

.PP
Get current warning message\&. 
.PP
\fBReturns:\fP
.RS 4
\fBcurrent_warning_msg\fP 
.RE
.PP

.SS "\fBRegexMatch\fP& jpcre2::Regex::initMatch ()\fC [inline]\fP"

.PP
Prepare to call \fBRegexMatch::match()\fP\&. Other options can be set with the setter functions of \fBRegexMatch\fP class in-between the \fBRegex::initMatch()\fP and \fBRegexMatch::match()\fP call\&. 
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::match()\fP 
.PP
\fBRegexMatch::setSubject(const String& s)\fP 
.PP
\fBRegexMatch::setModifier(const String& mod)\fP 
.PP
\fBRegexMatch::setNumberedSubstringVector(VecNum* vec_num)\fP 
.PP
\fBRegexMatch::setNamedSubstringVector(VecNas* vec_nas)\fP 
.PP
\fBRegexMatch::setNameToNumberMapVector(VecNtN* vec_ntn)\fP 
.RE
.PP

.SS "\fBRegexReplace\fP& jpcre2::Regex::initReplace ()\fC [inline]\fP"

.PP
Prepare to call \fBRegexReplace::replace()\fP\&. Other options can be set with the setter functions of \fBRegexReplace\fP class in-between the \fBRegex::initReplace()\fP and \fBRegexReplace::replace()\fP call\&. 
.PP
\fBSee also:\fP
.RS 4
\fBRegexReplace::replace()\fP 
.PP
\fBRegexReplace::setSubject(const String& s)\fP 
.PP
\fBRegexReplace::setModifier(const String& mod)\fP 
.PP
\fBRegexReplace::setReplaceWith(const String& s)\fP 
.PP
\fBRegexReplace::setBufferSize(PCRE2_SIZE x)\fP 
.RE
.PP

.SS "\fBSIZE_T\fP jpcre2::Regex::match (const \fBString\fP & s, const \fBString\fP & mod)\fC [inline]\fP"

.PP
Perform regex match\&. This function takes the parameters, then passes the parameters to the appropriate function \fBRegexMatch::match(const String& s, const String& mod)\fP which returns the result 
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::match(const String& s, const String& mod)\fP 
.RE
.PP

.PP
References jpcre2::RegexMatch::match()\&.
.SS "\fBSIZE_T\fP jpcre2::Regex::match (const \fBString\fP & s)\fC [inline]\fP"

.PP
Perform regex match\&. This function takes the parameters, then passes the parameters to the appropriate function \fBRegexMatch::match(const String& s)\fP which returns the result 
.PP
\fBSee also:\fP
.RS 4
\fBRegexMatch::match(const String& s)\fP 
.RE
.PP

.PP
References jpcre2::RegexMatch::match()\&.
.SS "\fBRegex\fP& jpcre2::Regex::operator= (const \fBRegex\fP & r)\fC [inline]\fP"

.PP
Overloaded assignment operator\&. Performs a deep copy 
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::removeJpcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Remove option from existing JPCRE2 option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::removePcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Remove option from existing PCRE2 option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBString\fP jpcre2::Regex::replace (const \fBString\fP & mains, const \fBString\fP & repl, const \fBString\fP & mod)\fC [inline]\fP"

.PP
Perform regex replace\&. This function takes the parameters, then passes the parameters to the appropriate function \fBRegexReplace::replace(const String& s, const String& r, const String& m)\fP which returns the result 
.PP
\fBSee also:\fP
.RS 4
\fBRegexReplace::replace(const String& s, const String& r, const String& m)\fP 
.RE
.PP

.PP
References jpcre2::RegexReplace::replace()\&.
.PP
Referenced by jpcre2::RegexReplace::replace()\&.
.SS "\fBString\fP jpcre2::Regex::replace (const \fBString\fP & mains, const \fBString\fP & repl)\fC [inline]\fP"

.PP
Perform regex replace\&. This function takes the parameters, then passes the parameters to the appropriate function \fBRegexReplace::replace(const String& s, const String& r)\fP which returns the result 
.PP
\fBSee also:\fP
.RS 4
\fBRegexReplace::replace(const String& s, const String& r)\fP 
.RE
.PP

.PP
References jpcre2::RegexReplace::replace()\&.
.SS "\fBString\fP jpcre2::Regex::replace (const \fBString\fP & mains)\fC [inline]\fP"

.PP
Perform regex replace\&. This function takes the parameters, then passes the parameters to the appropriate function \fBRegexReplace::replace(const String& s)\fP which returns the result 
.PP
\fBSee also:\fP
.RS 4
\fBRegexReplace::replace(const String& s)\fP 
.RE
.PP

.PP
References jpcre2::RegexReplace::replace()\&.
.SS "\fBRegex\fP& jpcre2::Regex::reset ()\fC [inline]\fP"

.PP
Reset all class variables to its default (initial) state\&. 
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::setJpcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Set JPCRE2 option (overwrites existing option) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::setLocale (const \fBString\fP & x)\fC [inline]\fP"

.PP
Set the locale\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Locale string 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::setModifier (const \fBString\fP & x)\fC [inline]\fP"

.PP
Set the modifier (overwrites existing JPCRE2 and PCRE2 option)\&. Re-initializes the option bits for PCRE2 and JPCRE2 options, then sets the modifier\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Modifier string 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::setPattern (const \fBString\fP & re)\fC [inline]\fP"

.PP
Set the Pattern string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIre\fP Pattern string 
.RE
.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.SS "\fBRegex\fP& jpcre2::Regex::setPcre2Option (\fBUint\fP x)\fC [inline]\fP"

.PP
Set PCRE2 option (overwrites existing option) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Option value #return *this 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
