.TH "jpcre2::INFO" 3 "Fri Sep 9 2016" "Version 10.25.04" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::INFO \- Namespace to provide information about JPCRE2 library itself\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBNAME\fP"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "const std::string \fBFULL_VERSION\fP"
.br
.RI "Full version string\&. "
.ti -1c
.RI "const std::string \fBVERSION_GENRE\fP"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "const std::string \fBVERSION_MAJOR\fP"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "const std::string \fBVERSION_MINOR\fP"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "const std::string \fBVERSION_PRE_RELEASE\fP"
.br
.RI "Alpha or beta (testing) release version\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace to provide information about JPCRE2 library itself\&. 

Contains constant Strings with version info\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBjpcre2::String\fP jpcre2::INFO::NAME"

.PP
Name of the project\&. 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
