.TH "jpcre2.cpp" 3 "Wed Sep 7 2016" "Version 10.25.02" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.cpp \- Define functions and global constants declared in \fBjpcre2\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'jpcre2\&.hpp'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstring>\fP
.br

.SH "Detailed Description"
.PP 
Define functions and global constants declared in \fBjpcre2\&.hpp\fP\&. 


.PP
.nf

.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
