.TH "jpcre2::ERROR" 3 "Sun Sep 11 2016" "Version 10.26.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::ERROR \- Namespace for error codes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBINVALID_MODIFIER\fP = 2, \fBJIT_COMPILE_FAILED\fP = 3 }
.RI "ERROR numbers\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace for error codes\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBERROR\fP numbers\&. JPCRE2 error numbers are positive integers while PCRE2 error numbers are negative integers\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINVALID_MODIFIER \fP\fP
Error number implying that invalid modifier was detected\&. 
.TP
\fB\fIJIT_COMPILE_FAILED \fP\fP
Error number implying that JIT compile failed\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
