.TH "jpcre2::ERROR" 3 "Tue Sep 6 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::ERROR \- Namespace for error codes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"
.SH "Detailed Description"
.PP 
Namespace for error codes\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBERROR\fP codes that are thrown in case error occurs\&. JPCRE2 error codes are positive integers while PCRE2 error codes are negative integers\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINVALID_MODIFIER \fP\fP
Error to be thrown when invalid modifier detected\&. 
.TP
\fB\fIJIT_COMPILE_FAILED \fP\fP
Error to be thrown when JIT compile fails\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
