.TH "test_match.cpp" 3 "Sun Sep 4 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_match.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'jpcre2\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
Vector to store numbured substring Map\&.
.PP
Vector to store named substring Map\&.
.PP
Vector to store Named substring to Number Map\&.
.PP
An empty object is not supposed to throw any exception in normal cases\&.
.PP
Compile the pattern
.PP
subject string
.PP
Now let's access the matched data
.PP
Each of these vectors contains a map and each of the maps contains all the substrings that are matched against the pattern\&. All the matches in all the maps combines the total match throughout the entire string\&.
.PP
This vector contains maps with number as the key and the corresponding substring as the value
.PP
This vector contains maps with name as the key and the corresponding substring as the value
.PP
This vector contains maps with name as the key and number as the value i\&.e the number (of substring) can be accessed with the name for named substring\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
