.TH "test_replace2.cpp" 3 "Sun Sep 11 2016" "Version 10.26.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_replace2.cpp \- Contains an example to take subject string, replacement string, modifier and pattern from user input and perform regex replace with JPCRE2\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contains an example to take subject string, replacement string, modifier and pattern from user input and perform regex replace with JPCRE2\&. 


.PP
.nf

#include <iostream>
#include "jpcre2\&.cpp"


#define getLine(a) std::getline(std::cin,a,'\n')


int main(){
    std::string pat,mod,subject,repl,repl_mod;

    std::cout<<"\nEnter pattern: ";
    getLine(pat);

    std::cout<<"\nEnter compile modifiers (eijmnsuxADJSU): ";
    getLine(mod);
    jpcre2::Regex re;   


    // Compile the pattern
    re\&.compile(pat,mod);
    
    //check if it was a success
    if(!re){std::cerr<<re\&.getErrorMessage();} //if(re) is only available for >=C++11, use if(!!re) as an alternative


    // subject string
    std::cout<<"\nEnter subject string (enter quit to quit): "<<std::endl;
    getLine(subject);
    if(subject=="quit")return 0;
     //replacement string
    std::cout<<"\nEnter replacement string: "<<std::endl;
    getLine(repl);

    std::cout<<"\nEnter action (replacement) modifiers (eEgx): ";
    getLine(repl_mod);

    //perform replace

    std::cout<<"\nreplaced string: "<<
        re\&.initReplace()
          \&.setSubject(subject)
          \&.setReplaceWith(repl)
          \&.addModifier(repl_mod)
          \&.replace();

    std::cout<<"\n\n--------------------------------------------------\n";

    return 0;
}

.fi
.PP
 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
