.TH "test_replace.cpp" 3 "Sun Sep 4 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_replace.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'jpcre2\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
An empty object is not supposed to throw any exception in normal cases\&.
.PP
Compile the pattern 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
