.TH "test_replace2.cpp" 3 "Sun Sep 4 2016" "Version 10.25.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_replace2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'jpcre2\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBgetLine\fP(a)   std::getline(std::cin,a,'\\n');"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define getLine(a)   std::getline(std::cin,a,'\\n');"

.SH "Function Documentation"
.PP 
.SS "int main ()"
An empty object is not supposed to throw any exception in normal cases\&.
.PP
Compile the pattern
.PP
subject string
.PP
replacement string
.PP
2 is the length of the returned string\&. Though, it will be expanded as needed, pass a large enough value to contain the string, otherwise internal substitute function will be called twice which will eat up some additional resource\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
