#!/bin/bash

dir="$1"
type="$2"
op="$3"
overwrite=false
allover=false
[[ $op = -o ]] && overwrite=true
[[ $3 = -oa ]] && allover=true && overwrite=true
[[ "$1" = "" || "$1" = . || "$1" = .. ]] && echo failed && exit 1 
[[ "$2" = "" || "$2" = . || "$2" = .. ]] && echo failed && exit 1 
list="$(find "$dir" -type f -printf "%p \\\\\n" | sed 's/^/\t/')"
if grep -qs -e "dist_${dir}_${type}[[:blank:]]*=" Makefile.am 2>/dev/null && ! $overwrite; then
	if ! $allover; then 
		echo "dist_${dir}_${type} += \\
${list/%\\/}" >> Makefile.am
	fi
else
	if ! $allover; then 
		echo "dist_${dir}_${type} = \\
${list/%\\/}" >> Makefile.am
	else
		echo "dist_${dir}_${type} = \\
${list/%\\/}" > Makefile.am
	fi
fi

