jpcre2::RegexMatch
Regex* jpcre2::RegexMatch::re
This is used to access private members in Regex.
Referenced by jpcre2::Regex::match, jpcre2::Regex::initMatch.
String jpcre2::RegexMatch::m_subject
Subject string for match.
Uint jpcre2::RegexMatch::match_opts
PCRE2 options for pcre2_match() (PCRE2 internal function)
Uint jpcre2::RegexMatch::jpcre2_match_opts
JPCRE2 options for match.
VecNum* jpcre2::RegexMatch::vec_num
Pointer to vector that will store the numbered substring maps.
VecNas* jpcre2::RegexMatch::vec_nas
Pointer to vector that will store the named substring maps.
VecNtN* jpcre2::RegexMatch::vec_ntn
Pointer to vector that will store the name to number maps.
MapNum* jpcre2::RegexMatch::num_map0
Pointer to map that will store numbered substrings temporarily.
MapNas* jpcre2::RegexMatch::nas_map0
Pointer to map that will store named substrings temporarily.
MapNtN* jpcre2::RegexMatch::ntn_map0
Pointer to map that will store name to number mapping temporarily.
friend class Regex
Define class Regex as friend and thus allow Regex to create object of this class.
void jpcre2::RegexMatch::getNumberedSubstrings(int, pcre2_match_data *)
Populate num_map0 with numbered substrings.
jpcre2::Except Throws exception with PCRE2 error number and error offset. rc Return value from pcre2_match() match_data pcre2 match data
References jpcre2::utils::throwException, jpcre2::utils::toString.
void jpcre2::RegexMatch::getNamedSubstrings(int, int, PCRE2_SPTR, pcre2_match_data *)
Populate nas_map0 and/or ntn_map0 with named substring and/or name to number mapping.
jpcre2::Except Throws exception with PCRE2 error number and error offset. namecount Number of capture group name name_entry_size Size of each entry in the name table. tabptr Pointer to name table match_data PCRE2 match data
References jpcre2::utils::throwException, jpcre2::utils::toString.
void jpcre2::RegexMatch::pushMapsIntoVectors(void)
Push maps into the vectors pointed by vec_num, vec_nas and vec_ntn and thus store match results in them.
void jpcre2::RegexMatch::init_vars()
Initialize class variables.
Do not call this without releasing vector/map memory.
jpcre2::RegexMatch::RegexMatch()
Default constructor.
Initialize class variables.
jpcre2::RegexMatch::RegexMatch(const RegexMatch &)
This is a copy constructor which is only used to prevent public object creation.
No need to implement it completely.
jpcre2::RegexMatch::~RegexMatch()
Destructor.
Deletes the temporary maps that were created to store substrings
RegexMatch& jpcre2::RegexMatch::setNumberedSubstringVector(VecNum *v)
Set a pointer to the numbered substring vector of type jpcre2::VecNum.
v vec_num RegexMatch&
RegexMatch& jpcre2::RegexMatch::setNamedSubstringVector(VecNas *v)
Set a pointer to the named substring vector of type jpcre2::VecNas.
v vec_nas RegexMatch&
RegexMatch& jpcre2::RegexMatch::setNameToNumberMapVector(VecNtN *v)
Set a pointer to the name to number map vector of type jpcre2::VecNtN.
v vec_ntn RegexMatch&
RegexMatch& jpcre2::RegexMatch::setSubject(const String &s)
Set the subject string m_subject.
s Subject string RegexMatch& RegexReplace::setSubject()
Referenced by jpcre2::Regex::match.
RegexMatch& jpcre2::RegexMatch::setModifier(const String &s)
Set the modifier (overwrites existing JPCRE2 and PCRE2 option).
Re-initializes the option bits for PCRE2 and JPCRE2 options, then parses the modifier to set their equivalent options.Note: If speed of operation is very crucial, use RegexMatch::setJpcre2Option() and RegexMatch::setPcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER as error number if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL is set and a wrong modifier was encountered. s Modifier string RegexMatch& RegexReplace::setModifier() Regex::setModifier()
Referenced by jpcre2::Regex::match.
RegexMatch& jpcre2::RegexMatch::setJpcre2Option(Uint x)
Set JPCRE2 option jpcre2_match_opts (overwrite existing option)
x Option value RegexMatch& RegexReplace::setJpcre2Option() Regex::setJpcre2Option()
RegexMatch& jpcre2::RegexMatch::setPcre2Option(Uint x)
Set PCRE2 option match_opts (overwrite existing option)
x Option value RegexMatch& RegexReplace::setPcre2Option() Regex::setPcre2Option()
RegexMatch& jpcre2::RegexMatch::setFindAll(bool x)
Set whether to perform global match.
x True or False RegexMatch&
References jpcre2::FIND_ALL.
RegexMatch& jpcre2::RegexMatch::setFindAll()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This function just calls RegexMatch::setFindAll(bool x) with true as the parameter.
RegexMatch&
jpcre2::RegexMatch & jpcre2::RegexMatch::changeModifier(const String &, bool)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
After a call to this function match_opts and jpcre2_match_opts will be properly set.This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to their default values before calling this function.Note: If speed of operation is very crucial, use RegexMatch::changeJpcre2Option() and RegexMatch::changePcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL was set and a wrong modifier was encountered. mod Modifier string x Whether to add or remove options RegexMatch& RegexReplace::changeModifier() Regex::changeModifier()
References jpcre2::Regex::changeJpcre2Option, jpcre2::Regex::changePcre2Option, jpcre2::ERROR_ALL, jpcre2::utils::getErrorMessage, jpcre2::ERROR::INVALID_MODIFIER, jpcre2::MOD::M_N, jpcre2::MOD::M_V, jpcre2::MOD::MJ_N, jpcre2::MOD::MJ_V, jpcre2::utils::throwException, jpcre2::VALIDATE_MODIFIER.
RegexMatch& jpcre2::RegexMatch::changeJpcre2Option(Uint opt, bool x)
Add or remove a JPCRE2 option.
opt JPCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexReplace::changeJpcre2Option() Regex::changeJpcre2Option()
RegexMatch& jpcre2::RegexMatch::changePcre2Option(Uint opt, bool x)
Add or remove a PCRE2 option.
opt PCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexReplace::changePcre2Option() Regex::changePcre2Option()
RegexMatch& jpcre2::RegexMatch::addModifier(const String &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
This is just a wrapper of the original function RegexMatch::changeModifier() provided for convenience.Note: If speed of operation is very crucial, use RegexMatch::addJpcre2Option() and RegexMatch::addPcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER as error number if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL is set and a wrong modifier was encountered. mod Modifier string RegexMatch& RegexReplace::addModifier() Regex::addModifier()
RegexMatch& jpcre2::RegexMatch::addJpcre2Option(Uint x)
Add option to existing JPCRE2 options jpcre2_match_opts.
x Option value RegexMatch& RegexReplace::addJpcre2Option() Regex::addJpcre2Option()
RegexMatch& jpcre2::RegexMatch::addPcre2Option(Uint x)
Add option to existing PCRE2 options match_opts.
x Option value RegexMatch& RegexReplace::addPcre2Option() Regex::addPcre2Option()
jpcre2::SIZE_T jpcre2::RegexMatch::match(void)
Store match result in vectors and return the number of matches.
Clear the specified vectors (vec_num, vec_nas, vec_ntn) and re-fill them with match results, then return the match count.The size of each vectors should be equal to the match count. The return value is guaranteed to give you the right match count. jpcre2::Except Throws exception with PCRE2 error number and error offset. Number of matches found SIZE_T Regex::match(const String& s) SIZE_T Regex::match(const String& s, const String& mod)
References jpcre2::FIND_ALL, jpcre2::utils::throwException.
Referenced by jpcre2::Regex::match.