jpcre2::Regex
RegexMatch* jpcre2::Regex::rm
Pointer to RegexMatch object.
Referenced by deepCopy.
RegexReplace* jpcre2::Regex::rr
Pointer to RegexReplace object.
Referenced by deepCopy.
String jpcre2::Regex::pat_str
Pattern string.
Referenced by compile, shallowCopy.
pcre2_code* jpcre2::Regex::code
Pointer to compiled pattern.
Referenced by deepCopy, compile.
Uint jpcre2::Regex::compile_opts
Compile options for PCRE2 (used by PCRE2 internal function pcre2_compile())
Referenced by getModifier, compile, shallowCopy.
Uint jpcre2::Regex::jpcre2_compile_opts
Compile options specific to JPCRE2.
Referenced by getModifier, deepCopy, changeModifier, compile, shallowCopy.
String jpcre2::Regex::mylocale
Locale as a string.
Referenced by compile, shallowCopy.
String jpcre2::Regex::current_warning_msg
Current warning message.
Referenced by deepCopy, changeModifier, compile, shallowCopy.
friend class RegexMatch
Define RegexMatch as friends. It needs to access the compiled pattern which is a private property of this class.
friend class RegexReplace
Define RegexReplace as friends. It needs to access the compiled pattern which is a private property of this class.
void jpcre2::Regex::init_vars()
Initialize class variables.
References jpcre2::LOCALE_DEFAULT.
void jpcre2::Regex::init()
Call Regex::init_vars() and initialize class variables.
This function should not be attempted to call after creating object. To re-initialize class variables at a later stage after creating object, use the Regex::reset() function. This function is private and should remain as such.
void jpcre2::Regex::init(const String &re, const String &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
re Regex pattern mod Modifier string
void jpcre2::Regex::init(const String &re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
re Regex pattern po PCRE2 options jo JPCRE2 options
void jpcre2::Regex::freeRegexMemory(void)
Free code if it's non-NULL.
Referenced by deepCopy.
void jpcre2::Regex::shallowCopy(const Regex &r)
Do a shallow copy of class variables.
References pat_str, mylocale, compile_opts, jpcre2_compile_opts, current_warning_msg.
void jpcre2::Regex::deepCopy(const Regex &)
Do a deep copy of rm, rr and code.
Copy compiled pattern to a new location, free the old memory and set the new pointer to code. jpcre2::Except Throws exception with PCRE2 error number and error offset. r Regex&
References code, current_warning_msg, jpcre2::ERROR_ALL, freeRegexMemory, jpcre2::utils::getPcre2ErrorMessage, jpcre2::JIT_COMPILE, jpcre2::ERROR::JIT_COMPILE_FAILED, jpcre2::JIT_ERROR_MESSAGE_PREFIX, jpcre2_compile_opts, rm, rr, jpcre2::utils::throwException.
jpcre2::Regex::Regex()
Default Constructor.
Initializes all class variables to defaults. Does not perform any compilation, and thus not expected to throw any exception.
jpcre2::Regex::Regex(const String &re)
Compile pattern with initialization.
jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string
jpcre2::Regex::Regex(const String &re, const String &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Compile pattern. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string mod Modifier string
jpcre2::Regex::Regex(const String &re, Uint pcre2_opts)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Compile pattern. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string pcre2_opts PCRE2 option value
jpcre2::Regex::Regex(const String &re, Uint pcre2_opts, Uint opt_bits)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Compiles pattern. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string pcre2_opts PCRE2 option value opt_bits JPCRE2 option value
jpcre2::Regex::Regex(const Regex &r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Copy constructor.
Performs a deep copy. jpcre2::Except Throws exception with PCRE2 error number and error offset r const Regex&
Regex& jpcre2::Regex::operator=(const Regex &r)
Overloaded assignment operator.
Performs a deep copy.Allows assigning objects like this: Regexre; re=Regex("newpattern"); However, use of this method is discouraged (Use Regex::compile() instead), because a call to this function requires an additional call to PCRE2 internal function pcre2_code_copy(). If the pattern was JIT compiled, it requires another additional JIT compilation because JIT memory was not copied by pcre2_code_copy().Memory management: Old JIT memory will be released along with the old compiled code. jpcre2::Except Throws exception with PCRE2 error number and error offset r const Regex& *this
jpcre2::Regex::~Regex()
Destructor Deletes memory used by rm an rr.
Regex& jpcre2::Regex::reset()
Reset all class variables to its default (initial) state.
Release any memory used by existing compiled pattern. *this
jpcre2::String jpcre2::Regex::getModifier()
Get modifier string calculated from JPCRE2 and PCRE2 options.
Calculate modifier string from compile_opts and jpcre2_compile_opts and return it.Note that, this only gives you the modifiers used for pattern compilation. There is no such function to get the action modifiers and neither there's any need for it as action modifiers are required to be passed anew with every action. On the other hand, you may set some modifiers to the Regex object and forget about it later or you may want to get the existing modifier and compile the regex again by modifying the existing ones.Do remember that modifiers (or PCRE2 and JPCRE2 options) do not change or get initialized as long as you don't do that explicitly. Calling Regex::setModifier() will re-set them.Mixed or combined modifier.Some modifier may include other modifiers i.e they have the same meaning of some modifiers combined together. For example, the 'n' modifier includes the 'u' modifier and together they are equivalent to PCRE2_UTF | PCRE2_UCP. When you set a modifier like this, both options get set, and when you remove (Regex::changeModifier()) the 'n', both will get removed Calculated modifier string
References jpcre2::MOD::C_N, jpcre2::MOD::C_V, jpcre2::MOD::CJ_N, jpcre2::MOD::CJ_V, compile_opts, jpcre2_compile_opts.
String jpcre2::Regex::getPattern()
Get pattern string.
pat_str
String jpcre2::Regex::getLocale()
Get locale as a string.
mylocale
Uint jpcre2::Regex::getPcre2Option()
Get PCRE2 option.
compile_opts
Uint jpcre2::Regex::getJpcre2Option()
Get JPCRE2 option.
jpcre2_compile_opts
String jpcre2::Regex::getWarningMessage()
Get current warning message.
current_warning_msg
Regex& jpcre2::Regex::setPattern(const String &re)
Set the Pattern string pat_str.
re Pattern string Regex&
Regex& jpcre2::Regex::setModifier(const String &x)
Set the modifier (overwrite existing JPCRE2 and PCRE2 option).
Re-initializes the option bits for PCRE2 and JPCRE2 options, then parses the modifier and sets equivalent PCRE2 and JPCRE2 options.Note: If speed of operation is very crucial, use Regex::setJpcre2Option() and Regex::setPcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER as error number if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL is set and a wrong modifier was encountered. x Modifier string Regex& RegexMatch::setModifier() RegexReplace::setModifier()
Regex& jpcre2::Regex::setLocale(const String &x)
Set the locale mylocale.
x Locale string Regex&
Regex& jpcre2::Regex::setJpcre2Option(Uint x)
Set JPCRE2 option jpcre2_compile_opts (overwrites existing option)
x Option value Regex& RegexMatch::setJpcre2Option() RegexReplace::setJpcre2Option()
Regex& jpcre2::Regex::setPcre2Option(Uint x)
Set PCRE2 option compile_opts (overwrites existing option)
x Option value Regex& RegexMatch::setPcre2Option() RegexReplace::setPcre2Option()
jpcre2::Regex & jpcre2::Regex::changeModifier(const String &, bool)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
After a call to this function compile_opts and jpcre2_compile_opts will be properly set.This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to 0 before calling this function.Note: If speed of operation is very crucial, use Regex::changeJpcre2Option() and Regex::changePcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL was set and a wrong modifier was encountered. mod Modifier string x Whether to add or remove option Regex& RegexMatch::changeModifier() RegexReplace::changeModifier()
References jpcre2::MOD::C_N, jpcre2::MOD::C_V, changeJpcre2Option, changePcre2Option, jpcre2::MOD::CJ_N, jpcre2::MOD::CJ_V, current_warning_msg, jpcre2::ERROR_ALL, jpcre2::utils::getErrorMessage, jpcre2::ERROR::INVALID_MODIFIER, jpcre2_compile_opts, jpcre2::utils::throwException, jpcre2::VALIDATE_MODIFIER.
Regex& jpcre2::Regex::changeJpcre2Option(Uint opt, bool x)
Add or remove a JPCRE2 option.
opt JPCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexMatch::changeJpcre2Option() RegexReplace::changeJpcre2Option()
Referenced by jpcre2::RegexMatch::changeModifier, jpcre2::RegexReplace::changeModifier, changeModifier.
Regex& jpcre2::Regex::changePcre2Option(Uint opt, bool x)
Add or remove a PCRE2 option.
opt PCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexMatch::changePcre2Option() RegexReplace::changePcre2Option()
Referenced by jpcre2::RegexMatch::changeModifier, jpcre2::RegexReplace::changeModifier, changeModifier.
Regex& jpcre2::Regex::addModifier(const String &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
This is just a wrapper of the original function Regex::changeModifier() provided for convenience.Note: If speed of operation is very crucial, use Regex::addJpcre2Option() and Regex::addPcre2Option() with equivalent options. It will be faster that way. jpcre2::Except Throws exception with ERROR::INVALID_MODIFIER as error number if jpcre2::VALIDATE_MODIFIER or jpcre2::ERROR_ALL is set and a wrong modifier was encountered. is set and a wrong modifier was encountered. mod Modifier string Regex& RegexMatch::addModifier() RegexReplace::addModifier()
Regex& jpcre2::Regex::addJpcre2Option(Uint x)
Add option to existing JPCRE2 options jpcre2_compile_opts.
x Option value Regex& RegexMatch::addJpcre2Option() RegexReplace::addJpcre2Option()
Regex& jpcre2::Regex::addPcre2Option(Uint x)
Add option to existing PCRE2 options compile_opts.
x Option value Regex& RegexMatch::addPcre2Option() RegexReplace::addPcre2Option()
void jpcre2::Regex::compile(void)
Compile the regex pattern from class variable pat_str.
Use options from class variables.Prefer using one of its variants when compiling pattern for an already declared Regex object. A use of re=Regex("pattern"); (or such) is discouraged. see Regex::operator=(const Regex& r) for details. jpcre2::Except Throws exception with PCRE2 error number and error offset. void compile(const String& re, Uint po, Uint jo) void compile(const String& re, Uint po) void compile(const String& re, const String& mod) void compile(const String& re)
References code, compile_opts, current_warning_msg, jpcre2::ERROR_ALL, jpcre2::utils::getPcre2ErrorMessage, jpcre2::JIT_COMPILE, jpcre2::ERROR::JIT_COMPILE_FAILED, jpcre2_compile_opts, jpcre2::LOCALE_NONE, mylocale, pat_str, jpcre2::utils::throwException, jpcre2::utils::toString.
void jpcre2::Regex::compile(const String &re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Set the specified parameters, then compile the pattern using information from class variables. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string po PCRE2 option jo JPCRE2 option
void jpcre2::Regex::compile(const String &re, Uint po)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Set the specified parameters, then compile the pattern using options from class variables. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string po PCRE2 option
void jpcre2::Regex::compile(const String &re, const String &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Set the specified parameters, then compile the pattern using options from class variables. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string mod Modifier string
void jpcre2::Regex::compile(const String &re)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Set the specified parameters, then compile the pattern using options from class variables. jpcre2::Except Throws exception with PCRE2 error number and error offset re Pattern string
SIZE_T jpcre2::Regex::match(const String &s, const String &mod)
Perform regex match and return match count.
This function takes the parameters, then sets the parameters to RegexMatch class and calls RegexMatch::match() which returns the result jpcre2::Except Throws exception with PCRE2 error number and error offset s Subject string mod Modifier string Match count RegexMatch::match()
References jpcre2::RegexMatch::match, jpcre2::RegexMatch::re, jpcre2::RegexMatch::setModifier, jpcre2::RegexMatch::setSubject.
SIZE_T jpcre2::Regex::match(const String &s)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
jpcre2::Except Throws exception with PCRE2 error number and error offset s Subject string Match count
References jpcre2::RegexMatch::match, jpcre2::RegexMatch::re, jpcre2::RegexMatch::setSubject.
RegexMatch& jpcre2::Regex::initMatch()
Prepare to call RegexMatch::match().
Other options can be set with the setter functions of RegexMatch class in-between the Regex::initMatch() and RegexMatch::match() call. RegexMatch& RegexMatch::match() RegexMatch::setSubject(const String& s) RegexMatch::setModifier(const String& mod) RegexMatch::setNumberedSubstringVector(VecNum* vec_num) RegexMatch::setNamedSubstringVector(VecNas* vec_nas) RegexMatch::setNameToNumberMapVector(VecNtN* vec_ntn)
References jpcre2::RegexMatch::re.
String jpcre2::Regex::replace(const String &mains, const String &repl, const String &mod)
Perform regex replace and return the replaced string.
This function takes the parameters, then sets the parameters to RegexReplace class and calls RegexReplace::replace() which returns the result. jpcre2::Except Throws exception with PCRE2 error number and error offset mains Subject string repl String to replace with mod Modifier string Resultant string after regex replace RegexReplace::replace()
References jpcre2::RegexReplace::re, jpcre2::RegexReplace::replace, jpcre2::RegexReplace::setModifier, jpcre2::RegexReplace::setReplaceWith, jpcre2::RegexReplace::setSubject.
Referenced by jpcre2::RegexReplace::replace.
String jpcre2::Regex::replace(const String &mains, const String &repl)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
jpcre2::Except Throws exception with PCRE2 error number and error offset mains Subject string repl String to replace with Resultant string after regex replace RegexReplace::replace()
References jpcre2::RegexReplace::re, jpcre2::RegexReplace::replace, jpcre2::RegexReplace::setReplaceWith, jpcre2::RegexReplace::setSubject.
RegexReplace& jpcre2::Regex::initReplace()
Prepare to call RegexReplace::replace().
Other options can be set with the setter functions of RegexReplace class in-between the Regex::initReplace() and RegexReplace::replace() call. RegexReplace& RegexReplace::replace() RegexReplace::setSubject(const String& s) RegexReplace::setModifier(const String& mod) RegexReplace::setReplaceWith(const String& s) RegexReplace::setBufferSize(PCRE2_SIZE x)
References jpcre2::RegexReplace::re.