jpcre2::RegexReplace
Regex* jpcre2::RegexReplace::re
This is used to access private members in Regex.
Referenced by jpcre2::Regex::replace, jpcre2::Regex::initReplace.
String jpcre2::RegexReplace::r_subject
Subject string for replace.
String jpcre2::RegexReplace::r_replw
Replacement string i.e string to replace with.
Uint jpcre2::RegexReplace::replace_opts
PCRE2 options for pcre2_substitute() (PCRE2 internal function)
Uint jpcre2::RegexReplace::jpcre2_replace_opts
JPCRE2 options.
PCRE2_SIZE jpcre2::RegexReplace::buffer_size
Size of the resultant string after replacement.
friend class Regex
Define Regex as a friend so that it can create object of this class.
void jpcre2::RegexReplace::init_vars()
Initialize class variables.
References jpcre2::SUBSTITUTE_RESULT_INIT_SIZE.
jpcre2::RegexReplace::RegexReplace()
Default constructor.
Initialize class variables
jpcre2::RegexReplace::RegexReplace(const RegexReplace &)
This is a copy constructor which is only used to prevent public object creation.
No need to implement it completely
jpcre2::RegexReplace::~RegexReplace()
Destructor.
Nothing to be done here.
RegexReplace& jpcre2::RegexReplace::setSubject(const String &s)
Set the subject string r_subject.
s Subject string RegexReplace& RegexMatch::setSubject()
Referenced by jpcre2::Regex::replace.
RegexReplace& jpcre2::RegexReplace::setReplaceWith(const String &s)
Set the replacement string r_replw.
s String to replace with RegexReplace&
Referenced by jpcre2::Regex::replace.
RegexReplace& jpcre2::RegexReplace::setModifier(const String &s)
Set the modifier string (overwrites existing JPCRE2 and PCRE2 option).
Note: If speed of operation is very crucial, use RegexReplace::setJpcre2Option() and RegexReplace::setPcre2Option() with equivalent options. It will be faster that way. s Modifier string RegexReplace& RegexMatch::setModifier() Regex::setModifier()
Referenced by jpcre2::Regex::replace.
RegexReplace& jpcre2::RegexReplace::setBufferSize(PCRE2_SIZE x)
Set the initial buffer size (buffer_size) to be allocated for replaced string (used by PCRE2)
x Buffer size RegexReplace&
RegexReplace& jpcre2::RegexReplace::setJpcre2Option(Uint x)
Set JPCRE2 option jpcre2_replace_opts (overwrite existing option)
x Option value RegexReplace& RegexMatch::setJpcre2Option() Regex::setJpcre2Option()
RegexReplace& jpcre2::RegexReplace::setPcre2Option(Uint x)
Set PCRE2 option replace_opts (overwrite existing option)
x Option value RegexReplace& RegexMatch::setPcre2Option() Regex::setPcre2Option()
jpcre2::RegexReplace & jpcre2::RegexReplace::changeModifier(const String &mod, bool x)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
After a call to this function replace_opts and jpcre2_replace_opts will be properly set. This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to their defaults before calling this function.Note: If speed of operation is very crucial, use RegexReplace::changeJpcre2Option() and RegexReplace::changePcre2Option() with equivalent options. It will be faster that way. mod Modifier string x Whether to add or remove option RegexReplace& RegexMatch::changeModifier() Regex::changeModifier()
References jpcre2::Regex::changeJpcre2Option, jpcre2::Regex::changePcre2Option, jpcre2::ERROR_ALL, jpcre2::ERROR::INVALID_MODIFIER, jpcre2::MOD::R_N, jpcre2::MOD::R_V, jpcre2::MOD::RJ_N, jpcre2::MOD::RJ_V, jpcre2::utils::throwException, jpcre2::VALIDATE_MODIFIER.
RegexReplace& jpcre2::RegexReplace::changeJpcre2Option(Uint opt, bool x)
Add or remove a JPCRE2 option.
opt JPCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexMatch::changeJpcre2Option() Regex::changeJpcre2Option()
RegexReplace& jpcre2::RegexReplace::changePcre2Option(Uint opt, bool x)
Add or remove a PCRE2 option.
opt PCRE2 option value x Add the option if it's true, remove otherwise. Regex& RegexMatch::changePcre2Option() Regex::changePcre2Option()
RegexReplace& jpcre2::RegexReplace::addModifier(const String &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
This is just a wrapper of the original function RegexReplace::changeModifier() provided for convenience.Note: If speed of operation is very crucial, use RegexReplace::addJpcre2Option() and RegexReplace::addPcre2Option() with equivalent options. It will be faster that way. mod Modifier string RegexReplace& RegexMatch::addModifier() Regex::addModifier()
RegexReplace& jpcre2::RegexReplace::addJpcre2Option(Uint x)
Add specified JPCRE2 option to existing options jpcre2_replace_opts.
x Option value RegexReplace& RegexMatch::addJpcre2Option() Regex::addJpcre2Option()
RegexReplace& jpcre2::RegexReplace::addPcre2Option(Uint x)
Add specified PCRE2 option to existing options replace_opts.
x Option value RegexReplace& RegexMatch::addPcre2Option() Regex::addPcre2Option()
jpcre2::String jpcre2::RegexReplace::replace(void)
Returns the resultant string after performing regex replace.
Retrieves subject string, replacement string, modifier and other options from class variables. Regex::error_number Throws exception (error number) if error occurs. Replaced string
References jpcre2::Regex::replace, jpcre2::utils::throwException, jpcre2::utils::toString.
Referenced by jpcre2::Regex::replace.