jpcre2::utils
jpcre2::String jpcre2::utils::toString(int)
Converts an integer to String.
x Integer to be converted to jpcre2::String jpcre2::String
Referenced by jpcre2::Regex::compile, getErrorMessage, jpcre2::RegexMatch::getNamedSubstrings, jpcre2::RegexMatch::getNumberedSubstrings, getPcre2ErrorMessage, jpcre2::RegexReplace::replace.
jpcre2::String jpcre2::utils::toString(char)
Converts a char to String.
a char to be converted to jpcre2::String jpcre2::String
jpcre2::String jpcre2::utils::toString(const char *)
Converts const char* to String.
a const char* to be converted to jpcre2::String jpcre2::String
jpcre2::String jpcre2::utils::toString(PCRE2_UCHAR *)
Converts a PCRE2_UCHAR* to String.
a PCRE2_UCHAR* to be converted to jpcre2::String jpcre2::String
std::string jpcre2::utils::getPcre2ErrorMessage(int)
Get PCRE2 error message for an error number.
err_num PCRE2 error number Error message as jpcre2::String
References toString.
Referenced by jpcre2::Regex::compile, jpcre2::Regex::deepCopy, getErrorMessage.
std::string jpcre2::utils::getErrorMessage(int, int)
Get error message from error number and error offset.
Return error message according to error number and error offset. err_num Error number err_off Error offset Error message as a string
References getPcre2ErrorMessage, jpcre2::ERROR::INVALID_MODIFIER, jpcre2::ERROR::JIT_COMPILE_FAILED, jpcre2::JIT_ERROR_MESSAGE_PREFIX, toString.
Referenced by jpcre2::RegexMatch::changeModifier, jpcre2::RegexReplace::changeModifier, jpcre2::Regex::changeModifier, throwException.
void jpcre2::utils::throwException(int, int)
Used throughout JPCRE2 to throw exceptions.
jpcre2::Except Throws exception. Should be caught by reference. See jpcre2::Except for details. err_num Error number err_off Error offset
References getErrorMessage.
Referenced by jpcre2::RegexMatch::changeModifier, jpcre2::RegexReplace::changeModifier, jpcre2::Regex::changeModifier, jpcre2::Regex::compile, jpcre2::Regex::deepCopy, jpcre2::RegexMatch::getNamedSubstrings, jpcre2::RegexMatch::getNumberedSubstrings, jpcre2::RegexMatch::match, jpcre2::RegexReplace::replace.